### ISSUE TITLE
群晖dsm7.0  docker可视化安装需要配置什么环境

### ISSUE THREAD

**Issue by wanghuisenior** [typecho/Dockerfile#17]
![image](https://user-images.githubusercontent.com/9377248/164592888-33ab2475-c126-40a7-9f8d-3947c8b133be.png)
![image](https://user-images.githubusercontent.com/9377248/164592946-68cbe14d-fd48-4e0f-9cd0-e5f035e4e00a.png)
请问使用docker镜像启动，存储空间，端口和环境都需要配置什么呢，找不到群晖配置typecho的文档

**Comment by wuzhuwei111** [comment]
官方的镜像源做的不是很好，主要是两点，1，附件上传大小有限制；2，附件插入带IP地址，切换IP会导致附件失效。需要等官方修复。建议你使用80X86的镜像，目前没有以上问题。

**Comment by wuzhuwei111** [comment]
-p 8080:80
 -v /var/typecho:/app/usr

这是官方建议配置，可以参考
