### ISSUE TITLE
*-FPM方式安装之后，访问ip+9000端口，无法打开网页。还需要啥操作吗

### ISSUE THREAD

**Issue by himonster1** [typecho/Dockerfile#19]
`docker run --name typecho-server -p 9000:9000 -e TYPECHO_SITE_URL=https://your-domain.com -d joyqi/typecho:nightly-php7.4-fpm`

访问ip:9000提示无法访问此网站

**Comment by joyqi** [comment]
fpm 镜像提供的是 fastcgi 接口，并不能用网页访问，你需要的 apache 镜像

**Comment by himonster1** [comment]
可以用nginx吗
