### ISSUE TITLE
哪里有问题?

### ISSUE THREAD

**Issue by mzzsfy** [typecho/Dockerfile#2]
只要按说明尝试挂载/app/usr目录就会启动失败

```
docker run --name typecho  \
-v /data/docker/typecho/app/usr:/app/usr \
--restart always -e 'TIMEZONE=Asia/Shanghai' \
-e 'TYPECHO_INSTALL=1' \
-e 'TYPECHO_SITE_URL=http://127.0.0.1' \
-e 'TYPECHO_DB_ADAPTER=Pdo_SQLite' \
-e 'TYPECHO_DB_FILE=/app/usr/db/SQLite.db' \
 joyqi/typecho:nightly-php7.4
```

我也尝试过其他版本镜像,特别询问alpine系列镜像完全没法使用,不挂目录也不行

**Comment by mzzsfy** [comment]
> 更新一下这个项目，然后重新`build`一下镜像（之前的删掉）
> 
> ```
> ./build.sh -p 7.4 -o alpine php
> ```
> 
> 用这个新的镜像去run，看看能否成功

请问你你们有先进行测试吗

**Comment by mzzsfy** [comment]
我改777试试吧

**Comment by joyqi** [comment]
更新一下再build，我刚刚修复过了

**Comment by joyqi** [comment]
你得用这个项目里的脚本自己在本地build，docker hub上的镜像自动build时间是每天早上八点，十多个镜像build完要中午了
