### ISSUE TITLE
无法自动安装配置

### ISSUE THREAD

**Issue by psc1453** [typecho/Dockerfile#21]
我尝试使用docker-compose安装typecho，想要以bridge的网络配置方式让typecho连接上MariaDB，可是按照以下配置部署过后，初次登陆还是需要我填写数据库的信息，好像自动配置是无效的，不知为何

version: '2'

services:
   db:
     image: mariadb:latest
     volumes:
       - /root/Server-Apps/Typecho/MariaDB:/var/lib/mysql
     restart: always
     environment:
       MARIADB_ROOT_PASSWORD: typecho
       MARIADB_DATABASE: typecho
       MARIADB_USER: typecho
       MARIADB_PASSWORD: typecho

   typecho:
     depends_on:
       - db
     image: joyqi/typecho:nightly-php7.4-apache
     ports:
       - 8060:80
     restart: always
     environment:
       TIMEZONE: Asia/Shanghai
       TYPECHO_INSTALL: 1
       TYPECHO_SITE_URL: http://myHost:8060
       TYPECHO_DB_ADAPTER: Mysqli
       TYPECHO_DB_HOST: db
       TYPECHO_DB_PORT: 3306
       TYPECHO_DB_DATABASE: typecho
       TYPECHO_DB_USER: typecho
       TYPECHO_DB_PASSWORD: typecho
       TYPECHO_USER_NAME: myUserName
       TYPECHO_USER_PASSWORD: myPassword
       TYPECHO_USER_MAIL: myEmail

**Comment by zurica2013** [comment]
我也碰到了一样的问题

**Comment by psc1453** [comment]
> 我也碰到了一样的问题

我已经放弃了，去用Halo了

**Comment by zurica2013** [comment]
今天我尝试了小半天，终于解决了。我估计你的问题大概率跟我遇到的是一样的。其实程序并没有出错，只是在配置上缺少了必要的限制条件。我会专门开一个 issue 来解释
