### ISSUE TITLE
附件上传大小有限制,附件插入带IP地址，切换IP会导致附件失效,问题反馈！

### ISSUE THREAD

**Issue by jackloves111** [typecho/Dockerfile#22]
官方的镜像源目前有两点只要问题需要解决：
1，附件上传大小有限制；
2，附件插入带IP地址，切换IP会导致附件失效。

希望官方能看到并修复。目前使用80X86的镜像，没有以上问题。
关于问题的详细官方可以直接联系我的邮箱：zhuwei.wu@foxmail.com
另外，关于群晖的可视化docker配置，我也可以写一些教程。

**Comment by 0o0m0s** [comment]
> 官方的镜像源目前有两点只要问题需要解决： 1，附件上传大小有限制； 2，附件插入带IP地址，切换IP会导致附件失效。
> 
> 希望官方能看到并修复。目前使用80X86的镜像，没有以上问题。 关于问题的详细官方可以直接联系我的邮箱：[zhuwei.wu@foxmail.com](mailto:zhuwei.wu@foxmail.com) 另外，关于群晖的可视化docker配置，我也可以写一些教程。

附件大小可能是nginx的报错，报错信息如下：

`client intended to send too large body: 3184393 bytes, client: 192.168.0.1, server: _, request: "POST /index.php/action/upload?cid=1&_=de8deb HTTP/1.1", host: "lyuan.co", referrer: "http://x x x x/admin/write-post.php?cid=1"`

在nginx配置文件中server段添加字段即可

```
server {

  client_max_body_size 20M;

} 
```
