### ISSUE TITLE
Tokenizer 似乎是不必安装的PHP extension?

### ISSUE THREAD

**Issue by zurica2013** [typecho/Dockerfile#23]
我尝试了用 build.sh 构建镜像，总是会发生错误而终止：
```
make: *** No rule to make target '/usr/src/php/ext/tokenizer/Zend/zend_language_parser.y', needed by '/usr/src/php/ext/tokenizer/Zend/zend_language_parser.c'.  Stop.
```
查了下是因为在 Dockerfile 中安装了 tokenizer 这个扩展，删去相关内容问题就解决了。查到有说法是PHP的官方镜像已经自带了这个扩展 [#1231](https://github.com/docker-library/php/issues/1231)，而且我试了下成功修改后构建的镜像也支持 tokenizer
```
~# php -i | grep -i tokenizer
Tokenizer Support => enabled
```
所以这个不是必需的？php的版本是8.0和8.1

**Comment by joyqi** [comment]
看起来8.0自带了这个扩展
