### ISSUE TITLE
无法连接数据库

### ISSUE THREAD

**Issue by yunzimo** [typecho/Dockerfile#33]
命令：
```
docker run --name typecho-server \
	-p 8088:80 \
	-e TYPECHO_SITE_URL=https://xxxxx.top \
	-d joyqi/typecho:nightly-php7.4-apache
```
一开始我看其他issue以为是文件权限的问题，因为我一开始的命令是：
```
docker run --name typecho-server \
	-p 8088:80 \
	-v $PWD/typecho/app/usr:/app/usr \
	-v $PWD/typecho/app/usr/plugins:/app/usr/plugins \
	-v $PWD/typecho/app/usr/themes:/app/usr/themes \
	-v $PWD/typecho/app/usr/uploads:/app/usr/uploads \
	-e TYPECHO_SITE_URL=https://xxxxxx.top \
	-d joyqi/typecho:nightly-php7.4-apache
```
我通过chmod修改用户权限后还是无法连接数据库，尝试最精简的命令也无法连接。
![image](https://github.com/typecho/Dockerfile/assets/45143713/e04fba37-2d5f-42f4-bb9f-cb604f3deb49)

请问这个docker镜像中存在数据库环境么，我是否需要自己安装数据库和其他环境，这让我感到迷惑，在初始化配置界面需要填的内容是我自己创建数据库的信息还是自动创建数据库需要填写的信息。

**Comment by loensos** [comment]
解决了吗？

**Comment by yunzimo** [comment]
> 

我尝试了只有SQLite类型的数据库适配器可以自动安装，其他的数据库不知道什么问题。

**Comment by yunzimo** [comment]
> 解决了吗？

我尝试了只有SQLite类型的数据库适配器可以自动安装，其他的数据库不知道什么问题。

**Comment by jkjoy** [comment]
赋权 777

**Comment by jkjoy** [comment]
应该是无法创建config文件报错
