### ISSUE TITLE
Docker容器部署后访问地址出现问题

### ISSUE THREAD

**Issue by z-hanzhe** [typecho/Dockerfile#37]
## 资源介绍

操作系统：Ubuntu Server 22.04
Docker版本：Docker Engine - Community 24.0.6
镜像版本：joyqi/typecho            nightly-php7.4-apache   ff6f2e2043f9   7 hours ago     495MB

## 使用场景

首先我在Docker中创建了一个网桥，这里用aaa代替网桥名称
```shell
docker network create aaa
```

然后将typecho和nginx都部署到aaa网桥上，typecho的容器名就叫typecho，启动命令如下所示：
```shell
docker run --name typecho \
   --restart always \
   --network aaa \
   -e TYPECHO_SITE_URL=https://typecho.domain.com \
   -d joyqi/typecho:nightly-php7.4-apache
```

在nginx配置文件中我是这么配置的
```conf
server {
    listen       443 ssl;
    server_name  typecho.domain.com;
    ssl_certificate         ***.crt;
    ssl_certificate_key  ***.key;

    location / {
        proxy_pass    http://typecho;
        index         index.html index.htm index.php;
    }

}
```

## 问题

在访问网站后发现请求静态资源时并没有使用我指定的`TYPECHO_SITE_URL`

![image](https://github.com/typecho/Dockerfile/assets/58802604/e5f58cf1-fcb1-43b9-a459-44cea7015b15)

请问是我的操作有问题吗？

**Comment by z-hanzhe** [comment]
问题已经解决了，修改Nginx配置文件可以解决该问题

```conf
    location / {
        proxy_pass           http://typecho;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto https;
        index                    index.html index.htm index.php;
    }
```

**Comment by x1ntt** [comment]
你现在用的什么方案？默认似乎是apache，你这个是nginx？有对应tag是nginx吗？

**Comment by z-hanzhe** [comment]
> 你现在用的什么方案？默认似乎是apache，你这个是nginx？有对应tag是nginx吗？

纯粹是我自己没配置好，问题已经解决了
