### ISSUE TITLE
容器报错Bus error (core dumped)，是否可查看更多debug信息

### ISSUE THREAD

**Issue by lwabish** [typecho/Dockerfile#38]
跑在k8s里，使用的是joyqi/typecho:1.2.0-php7.4-fpm-alpine这个镜像。
节点vm开启大页内存时，容器无法正常运行。
日志：
>PHP Warning:  Use of undefined constant __TYPECHO_SECURE__ - assumed '__TYPECHO_SECURE__' (this will throw an Error in a future version of PHP) in /app/config.inc.php on line 32
Typecho 1.2.0
PHP 7.4.28
Bus error (core dumped)

想进一步排查一下是什么问题，不知道能否获取到更多debug信息？

**Comment by joyqi** [comment]
看起来不是程序报错，应该是php报错，你有没有在 php 里面打开 Hugepage

**Comment by lwabish** [comment]
原来如此，当时是做实验开了vm的大页内存，我了解下php的hugepage去
