### ISSUE TITLE
nightly-php8.2-apache docker 安装后只能显示标题，无法显示文章内容

### ISSUE THREAD

**Issue by ainp** [typecho/Dockerfile#45]
只显示文章标题，打不开文章内容

**Comment by ainp** [comment]
nightly-php7.4-apache 也一样,启用了Facile,  设置了伪静态，也成功了，查看了.htaccess也正常

**Comment by ainp** [comment]
也无法预览文章

**Comment by ainp** [comment]
退回到1.2.1-php8.0-apache 就没有问题

**Comment by sy-records** [comment]
可以打开`debug`查看具体错误信息堆栈，在`config.inc.php`中加入：

```php
define('__TYPECHO_DEBUG__', true);
```

**Comment by ainp** [comment]
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.19.0.8. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.19.0.8. Set the 'ServerName' directive globally to suppress this message
[20-Apr-2024 07:09:53 UTC] PHP Warning:  PHP Startup: Unable to load dynamic library 'gd.so' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20220829/gd.so (libpng16.so.16: cannot open shared object file: No such file or directory), /usr/local/lib/php/extensions/no-debug-non-zts-20220829/gd.so.so (/usr/local/lib/php/extensions/no-debug-non-zts-20220829/gd.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
[20-Apr-2024 07:09:53 UTC] PHP Warning:  PHP Startup: Unable to load dynamic library 'zip.so' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20220829/zip.so (libzip.so.4: cannot open shared object file: No such file or directory), /usr/local/lib/php/extensions/no-debug-non-zts-20220829/zip.so.so (/usr/local/lib/php/extensions/no-debug-non-zts-20220829/zip.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
[Sat Apr 20 07:09:53.914372 2024] [mpm_prefork:notice] [pid 28] AH00163: Apache/2.4.57 (Debian) PHP/8.2.18 configured -- resuming normal operations
[Sat Apr 20 07:09:53.914739 2024] [core:notice] [pid 28] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'
172.19.0.2 - - [20/Apr/2024:07:10:05 +0000] "GET / HTTP/1.1" 302 255 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
172.19.0.2 - - [20/Apr/2024:07:10:06 +0000] "GET /install.php HTTP/1.1" 200 2854 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
172.19.0.2 - - [20/Apr/2024:07:10:10 +0000] "POST /install.php HTTP/1.1" 200 275 "https://blog.ainp.gay/install.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
172.19.0.2 - - [20/Apr/2024:07:10:11 +0000] "GET /install.php?step=2 HTTP/1.1" 200 3179 "https://blog.ainp.gay/install.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
172.19.0.2 - - [20/Apr/2024:07:11:23 +0000] "POST /install.php HTTP/1.1" 200 276 "https://blog.ainp.gay/install.php?step=2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
172.19.0.2 - - [20/Apr/2024:07:11:24 +0000] "GET /install.php?step=3 HTTP/1.1" 200 2256 "https://blog.ainp.gay/install.php?step=2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
172.19.0.2 - - [20/Apr/2024:07:11:36 +0000] "POST /install.php HTTP/1.1" 200 799 "https://blog.ainp.gay/install.php?step=3" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
172.19.0.2 - - [20/Apr/2024:07:11:43 +0000] "GET /index.php/action/login?name=ainp&password=Hy%40950930%26980519&referer=https%3A%2F%2Fblog.ainp.gay%2Fadmin%2F&_=15840d9f2cb8c8082a0dd84ab153f7fe HTTP/1.1" 302 506 "https://blog.ainp.gay/install.php?step=3" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
172.19.0.2 - - [20/Apr/2024:07:11:43 +0000] "GET /admin/ HTTP/1.1" 200 3946 "https://blog.ainp.gay/install.php?step=3" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
172.19.0.2 - - [20/Apr/2024:07:11:44 +0000] "GET /admin/js/typecho.js?v=1.3.0 HTTP/1.1" 200 6938 "https://blog.ainp.gay/admin/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
172.19.0.2 - - [20/Apr/2024:07:11:44 +0000] "GET /admin/js/jquery-ui.js?v=1.3.0 HTTP/1.1" 200 21959 "https://blog.ainp.gay/admin/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
172.19.0.2 - - [20/Apr/2024:07:11:44 +0000] "GET /index.php/action/ajax?do=feed HTTP/1.1" 200 1662 "https://blog.ainp.gay/admin/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
172.19.0.2 - - [20/Apr/2024:07:11:45 +0000] "GET /index.php/action/ajax?do=checkVersion HTTP/1.1" 200 361 "https://blog.ainp.gay/admin/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
172.19.0.2 - - [20/Apr/2024:07:11:51 +0000] "GET /admin/themes.php HTTP/1.1" 200 3701 "https://blog.ainp.gay/admin/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
172.19.0.2 - - [20/Apr/2024:07:11:52 +0000] "GET /usr/themes/Facile/screenshot.jpg HTTP/1.1" 200 20145 "https://blog.ainp.gay/admin/themes.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
172.19.0.2 - - [20/Apr/2024:07:11:54 +0000] "GET /index.php/action/themes-edit?change=Facile&_=3144a09902cfe96d4b4aca6423e9a5b5 HTTP/1.1" 302 9266 "https://blog.ainp.gay/admin/themes.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
172.19.0.2 - - [20/Apr/2024:07:11:54 +0000] "GET /admin/themes.php HTTP/1.1" 200 3459 "https://blog.ainp.gay/admin/themes.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
172.19.0.2 - - [20/Apr/2024:07:11:57 +0000] "GET /admin/plugins.php HTTP/1.1" 200 3757 "https://blog.ainp.gay/admin/themes.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
172.19.0.2 - - [20/Apr/2024:07:12:01 +0000] "GET /index.php/action/plugins-edit?activate=SMEditor&_=24ec2394d634811076a25531537d5356 HTTP/1.1" 302 776 "https://blog.ainp.gay/admin/plugins.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
172.19.0.2 - - [20/Apr/2024:07:12:01 +0000] "GET /admin/plugins.php HTTP/1.1" 200 3859 "https://blog.ainp.gay/admin/plugins.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
172.19.0.2 - - [20/Apr/2024:07:12:04 +0000] "GET /index.php/action/plugins-edit?activate=BaiduTextCensor&_=24ec2394d634811076a25531537d5356 HTTP/1.1" 302 1203 "https://blog.ainp.gay/admin/plugins.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
172.19.0.2 - - [20/Apr/2024:07:12:04 +0000] "GET /admin/plugins.php HTTP/1.1" 200 3822 "https://blog.ainp.gay/admin/plugins.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
172.19.0.2 - - [20/Apr/2024:07:12:06 +0000] "GET /admin/options-plugin.php?config=BaiduTextCensor HTTP/1.1" 200 4039 "https://blog.ainp.gay/admin/plugins.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
172.19.0.2 - - [20/Apr/2024:07:12:13 +0000] "POST /index.php/action/plugins-edit?config=BaiduTextCensor&_=1c3745626c3dff241f0fe33d9b8a8773 HTTP/1.1" 302 792 "https://blog.ainp.gay/admin/options-plugin.php?config=BaiduTextCensor" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
172.19.0.2 - - [20/Apr/2024:07:12:14 +0000] "GET /admin/plugins.php HTTP/1.1" 200 3822 "https://blog.ainp.gay/admin/options-plugin.php?config=BaiduTextCensor" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
172.19.0.2 - - [20/Apr/2024:07:12:20 +0000] "GET /admin/options-permalink.php HTTP/1.1" 200 4495 "https://blog.ainp.gay/admin/plugins.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
172.19.0.2 - - [20/Apr/2024:07:12:28 +0000] "POST /action/ajax HTTP/1.1" 200 231 "-" "Typecho 1.3.0"
[Sat Apr 20 07:12:28.516292 2024] [php:warn] [pid 31] [client 172.19.0.2:60242] PHP Warning:  Undefined array key "url" in /app/var/Widget/Options/Permalink.php on line 340, referer: https://blog.ainp.gay/admin/options-permalink.php
172.19.0.2 - - [20/Apr/2024:07:12:28 +0000] "POST /index.php/action/options-permalink?_=869dae2aa3ceceeb9288290d2562abe6 HTTP/1.1" 302 661 "https://blog.ainp.gay/admin/options-permalink.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"

172.19.0.2 - - [20/Apr/2024:07:12:28 +0000] "GET /admin/options-permalink.php HTTP/1.1" 200 4491 "https://blog.ainp.gay/admin/options-permalink.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
172.19.0.2 - - [20/Apr/2024:07:15:36 +0000] "GET / HTTP/1.1" 200 3813 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
172.19.0.2 - - [20/Apr/2024:07:15:37 +0000] "GET /usr/themes/Facile/assets/css/style-20230622.css HTTP/1.1" 200 52682 "https://blog.ainp.gay/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
172.19.0.2 - - [20/Apr/2024:07:15:37 +0000] "GET /usr/themes/Facile/assets/js/bundle-20230622.js HTTP/1.1" 200 89270 "https://blog.ainp.gay/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
172.19.0.2 - - [20/Apr/2024:07:15:45 +0000] "GET /default/1.html HTTP/1.1" 200 6693 "https://blog.ainp.gay/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
172.19.0.2 - - [20/Apr/2024:07:15:45 +0000] "POST /usr/themes/Facile/emoji.php HTTP/1.1" 200 4637 "https://blog.ainp.gay/default/1.html" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"

**Comment by ainp** [comment]
![截屏2024-04-20 15 18 50](https://github.com/typecho/Dockerfile/assets/9693302/9d12acbe-42a7-426c-8e5c-b5a17816119b)

**Comment by ainp** [comment]
我使用的cloudflare  隧道，新版本有问题。退回上个版本　1.2.1-php8.0-apache就没有问题

**Comment by ainp** [comment]
![截屏2024-04-20 15 31 50](https://github.com/typecho/Dockerfile/assets/9693302/194a3d8c-7e2f-4eeb-ad38-b72a7038f78a)
![截屏2024-04-20 15 32 01](https://github.com/typecho/Dockerfile/assets/9693302/fcd59a5f-073c-45a1-9f50-2d25a10465f2)

**Comment by sy-records** [comment]
没有用的信息，打开后看页面上的报错

**Comment by ainp** [comment]
打开后需要重启之类的吗？（页面上没有任何报错)

**Comment by sy-records** [comment]
应该不用重启，可以备份一下切到默认主题试试。 应该是主题不兼容新版本的问题

**Comment by ainp** [comment]
试用了默认主题和经典22主题都一样，打不开文章详情

**Comment by sy-records** [comment]
没有复现你的问题

<img width="1446" alt="image" src="https://github.com/typecho/Dockerfile/assets/33931153/a6b219dc-f510-4243-b160-e46b1c9f65f3">
