### ISSUE TITLE
fpm的版本都没办法打开页面

### ISSUE THREAD

**Issue by binjoo** [typecho/Dockerfile#46]
使用实例中的命令，`docker run --name typecho-server -p 9000:9000 -e TYPECHO_SITE_URL=https://your-domain.com -d joyqi/typecho:nightly-php7.4-fpm`，启动是成功的。

```bash
[22-Apr-2024 01:54:22] NOTICE: fpm is running, pid 33
[22-Apr-2024 01:54:22] NOTICE: ready to handle connections
```

日志也没有异常，但就是打不开页面。

**Comment by binjoo** [comment]
`joyqi/typecho:nightly-php7.4-fpm`更换成`joyqi/typecho:1.2.1-php7.4-fpm`也是一样的。

**Comment by sy-records** [comment]
Duplicate of #5
