### ISSUE TITLE
gd.so zip.so 异常

### ISSUE THREAD

**Issue by yi-shiyu** [typecho/Dockerfile#48]
![QQ20241010-224053](https://github.com/user-attachments/assets/93b374dc-e9b6-4ce2-9730-3d0c7bc1d95e)
扩展文件确实存在，问了GPT，执行 `apt update`  `apt install libpng-dev` `apt install libzip-dev` 正常

**Comment by sy-records** [comment]
你的 docker 命令是什么？

**Comment by yi-shiyu** [comment]
> 你的 docker 命令是什么？

系统Debian12
这是我的docker-compose.yaml ，`docker compose up -d`启的

[root 06:07:10 ~]$ cat /opt/blog/docker-compose.yaml 
version: '3.7'

services:
  typecho:
    image: joyqi/typecho:nightly-php8.2-apache
    container_name: typecho-server
    restart: always
    environment:
      - TYPECHO_SITE_URL=https://xxxx.xxx
    ports:
      - 30030:80
    volumes:
      - /opt/blog:/app/usr
