### ISSUE TITLE
joyqi/typecho:nightly-php7.4-fpm 无法打开。。连接被重置 对应端口也开放了。。

### ISSUE THREAD

**Issue by 287138531** [typecho/Dockerfile#5]
joyqi/typecho:nightly-php7.4-fpm 无法打开。。连接被重置 对应端口也开放了。。
docker日志如下
[03-Dec-2021 10:16:06] NOTICE: fpm is running, pid 19

[03-Dec-2021 10:16:06] NOTICE: ready to handle connections

Apache Image版本的就没问题

**Comment by joyqi** [comment]
你是用什么服务器连接fpm的，有没有error-log

**Comment by 287138531** [comment]
fpm方式，必须要搭配nginx这样的转发吗？我不太懂，就跑起来了fpm镜像，开放了对应端口，然后我就访问ip：9000，但是打不开

**Comment by joyqi** [comment]
🤦‍♂️，当然fpm是fastcgi协议，是给服务器识别的，中间要经过http服务器中转
