### ISSUE TITLE
关于 TIMEZONE

### ISSUE THREAD

**Issue by wordlesswind** [typecho/Dockerfile#6]
https://github.com/typecho/Dockerfile/blob/ee04d8e56b93c870313922ab13fff9470511c9cb/Dockerfile.base#L7

Debian 容器自带了一个 `TZ` 变量，用于修改系统时区，建议统一使用 `TZ` 作为变量名。

**Comment by joyqi** [comment]
`TIMEZONE`不仅用于修改系统时区，还用于修改PHP的时区，同时我们还需要同时兼容debian和alpine两种环境，后者并没有使用`TZ`环境变量

**Comment by wordlesswind** [comment]
> `TIMEZONE`不仅用于修改系统时区，还用于修改PHP的时区，同时我们还需要同时兼容debian和alpine两种环境，后者并没有使用`TZ`环境变量

Alpine Linux 有使用 `TZ` 变量，仅需安装 `tzdata` 即可使用。
