### ISSUE TITLE
nginx代理加载问题

### ISSUE THREAD

**Issue by BoyChai** [typecho/Dockerfile#7]
我是用nginx进行反向代理出现加载慢，只会加载html 如图
![image](https://user-images.githubusercontent.com/88495409/149906697-49901cc4-817a-4b34-8b70-4a3c01b1ad38.png)
![image](https://user-images.githubusercontent.com/88495409/149907259-47bbe91b-4131-4318-83e0-d0474b93ad01.png)
nginx反向代理的配置文件
![image](https://user-images.githubusercontent.com/88495409/149907244-f007b215-4d4f-44d4-a5a0-3eb94b75a840.png)

**Comment by Simplefish666** [comment]
> 我是用nginx进行反向代理出现加载慢，只会加载html 如图 ![image](https://user-images.githubusercontent.com/88495409/149906697-49901cc4-817a-4b34-8b70-4a3c01b1ad38.png) 
![image](https://user-images.githubusercontent.com/88495409/149907026-7327d8b5-51ff-4a6a-b6d0-9aef8b53fc24.png)

nginx反向代理的配置文件 
![image](https://user-images.githubusercontent.com/88495409/149906993-4ab6a7ac-5271-4c7d-86f3-64dd48c5123f.png)

**Comment by joyqi** [comment]
不经过反向代理，直接访问会有问题么

**Comment by colinsoo** [comment]
> 不经过反向代理，直接访问会有问题么

我也出现这样的问题，我用的是Nginx Proxy Manager，不经过反代的话就是好的。
tag：joyqi/typecho:nightly-php7.4-apache

**Comment by Nanmen** [comment]
> > 不经过反向代理，直接访问会有问题么
> 
> 我也出现这样的问题，我用的是Nginx Proxy Manager，不经过反代的话就是好的。 tag：joyqi/typecho:nightly-php7.4-apache

麻烦问下- -，你是群晖么？群晖部署的时候出现的初始化问题Could not initialize random number generator

**Comment by colinsoo** [comment]
> > > 不经过反向代理，直接访问会有问题么
> > 
> > 
> > 我也出现这样的问题，我用的是Nginx Proxy Manager，不经过反代的话就是好的。 tag：joyqi/typecho:nightly-php7.4-apache
> 
> 麻烦问下- -，你是群晖么？群晖部署的时候出现的初始化问题Could not initialize random number generator

我不是额，我用的腾讯云轻量，centos7

**Comment by Nanmen** [comment]
> > > > 不经过反向代理，直接访问会有问题么
> > > 
> > > 
> > > 我也出现这样的问题，我用的是Nginx Proxy Manager，不经过反代的话就是好的。 tag：joyqi/typecho:nightly-php7.4-apache
> > 
> > 
> > 麻烦问下- -，你是群晖么？群晖部署的时候出现的初始化问题Could not initialize random number generator
> 
> 我不是额，我用的腾讯云轻量，centos7

嗯，我知道了，经搜索得知，群晖的内核太低了，不支持apache的模式，只能上fpm方式。

**Comment by Dev-Wiki** [comment]
> > 不经过反向代理，直接访问会有问题么
> 
> 我也出现这样的问题，我用的是Nginx Proxy Manager，不经过反代的话就是好的。 tag：joyqi/typecho:nightly-php7.4-apache

manager 里面你开启了 force https 了么? 如果开启了 配置header了么?

**Comment by Nanmen** [comment]
> 

开启了，配置了的=-=，群晖目前我还没装好，我现在的体系是caddy2 + php-fpm 版本，Apache 的我装不上。劳驾问下，你装好了么？如果装好了，指教下- -

**Comment by kaking4** [comment]
我尝试在config.inc.php文件中添加，
define('__TYPECHO_SECURE__',true);
解决了此问题

**Comment by colinsoo** [comment]
![image](https://user-images.githubusercontent.com/61687281/165032096-0acea919-2bd1-41fc-8f40-93c0fd1d1ad1.png)
通过浏览器网络分析，我发现之前丢失样式是这里忘记更改了，改成htpps后用Nginx Proxy Manager反代正常。

**Comment by he0119** [comment]
如果要反代的话，需要设置一些 header 才能正确识别。下面是 `Nginx` 的配置。

```conf
location / {
    proxy_pass http://typecho:80;

    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}
```

**Comment by BoyChai** [comment]
> 
应该就是这个问题 我已经解决了

**Comment by junwd** [comment]
在站点地址里面可以看到地址是ip地址、改为域名即可正常
