### ISSUE TITLE
显示SQLSTATE[HY000] [2002] No such file or directory怎么办？

### ISSUE THREAD

**Issue by decidenow** [typecho/Dockerfile#8]
docker run --name typecho-server -p 8082:80 -v /var/typecho:/app/usr -e TYPECHO_SITE_URL=https://your-domain.com -e TYPECHO_DB_USER=typechous -e TYPECHO_DB_PASSWORD=typechopw -e TYPECHO_DB_DATABASE=typechodb -d joyqi/typecho:nightly-php7.4

我用以上的方法来运行docker的typecho 能进入网页但是选择数据库时显示SQLSTATE[HY000] [2002] No such file or directory怎么办？能教下我吗

**Comment by Hoexhe** [comment]
> docker run --name typecho-server -p 8082:80 -v /var/typecho:/app/usr -e TYPECHO_SITE_URL=https://your-domain.com -e TYPECHO_DB_USER=typechous -e TYPECHO_DB_PASSWORD=typechopw -e TYPECHO_DB_DATABASE=typechodb -d joyqi/typecho:nightly-php7.4
> 
> 我用以上的方法来运行docker的typecho 能进入网页但是选择数据库时显示SQLSTATE[HY000] [2002] No such file or directory怎么办？能教下我吗

`TYPECHO_DB_HOST` default: `localhost`。 而 `docker` 容器中没有 `mysql` 服务

**Comment by joyqi** [comment]
如 @Hoexhe 所说，typecho的容器中是没有内置mysql服务的，你需要自己启动一个
